person:
  userName: 张三
  boss: true
  birth: 2021/01/02
  age: 12
  pet:
    name: tom
    weight: 100.01
  interests: [足球,篮球,羽毛球]
  animal:
    - 兔子
    - 猫
  score: {英语:12,数学:100}
  salarys: [100.00,1002.31]
  allPets:
    sick:
      - name: tom
        weight: 100.01
      - name: to
        weight: 100.01
    health:
      - name: tom1
        weight: 100.01
      - name: to2
        weight: 100.01